from django.contrib import admin
from .models import *
from .models import M_DailyPlan
from .models import N_Session

# Register your models here.
admin.site.register(A_2020_January)
admin.site.register(B_2020_February)
admin.site.register(C_2020_March)
admin.site.register(D_2020_April)
admin.site.register(E_2020_May)
admin.site.register(F_2020_June)
admin.site.register(G_2020_July)
admin.site.register(H_2020_August)
admin.site.register(I_2020_September)
admin.site.register(J_2020_October)
admin.site.register(K_2020_November)
admin.site.register(L_2020_December)
admin.site.register(A_2021_January)
admin.site.register(B_2021_February)
admin.site.register(C_2021_March)
admin.site.register(D_2021_April)
admin.site.register(E_2021_May)
admin.site.register(F_2021_June)
admin.site.register(G_2021_July)
admin.site.register(H_2021_August)
admin.site.register(I_2021_September)
admin.site.register(J_2021_October)
admin.site.register(K_2021_November)
admin.site.register(L_2021_December)
admin.site.register(A_2022_January)
admin.site.register(B_2022_February)
admin.site.register(C_2022_March)
admin.site.register(D_2022_April)
admin.site.register(E_2022_May)
admin.site.register(F_2022_June)
admin.site.register(G_2022_July)
admin.site.register(H_2022_August)
admin.site.register(I_2022_September)
admin.site.register(J_2022_October)
admin.site.register(K_2022_November)
admin.site.register(L_2022_December)
admin.site.register(M_DailyPlan)
admin.site.register(N_Session)
admin.site.register(Z_Data)