# Generated by Django 3.1 on 2021-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_2021_january',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color10',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color11',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color12',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color13',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color15',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color16',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color17',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color18',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color19',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color2',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color20',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color21',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color22',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color23',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color24',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color25',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color26',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color27',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color28',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color29',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color3',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color30',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color31',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color32',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color33',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color34',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color35',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color36',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color37',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color38',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color39',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color4',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color40',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color41',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color42',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color5',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color6',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color7',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color8',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='a_2021_january',
            name='color9',
            field=models.CharField(default='rest', max_length=20),
        ),
    ]
