# Generated by Django 3.1 on 2021-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_auto_20210116_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_2021_january',
            name='color14',
            field=models.CharField(default='rest', max_length=20),
        ),
    ]
