# Generated by Django 3.1 on 2021-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_auto_20210116_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_2021_february',
            name='color1',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color10',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color11',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color12',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color13',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color14',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color15',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color16',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color17',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color18',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color19',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color2',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color20',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color21',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color22',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color23',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color24',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color25',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color26',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color27',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color28',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color29',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color3',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color30',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color31',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color32',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color33',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color34',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color35',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color36',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color37',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color38',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color39',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color4',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color40',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color41',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color42',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color5',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color6',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color7',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color8',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='b_2021_february',
            name='color9',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug1',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug10',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug11',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug12',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug2',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug3',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug4',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug5',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug6',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug7',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug8',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='n_session',
            name='slug9',
            field=models.SlugField(blank=True),
        ),
    ]
