# Generated by Django 3.1 on 2021-01-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0008_auto_20210118_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='j_2020_october',
            name='color36',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='j_2020_october',
            name='day_36',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='j_2020_october',
            name='slug_day_36',
            field=models.SlugField(default='off'),
        ),
    ]
