# Generated by Django 3.1 on 2021-01-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0009_auto_20210118_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='i_2020_september',
            name='color7',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='i_2020_september',
            name='day_7',
            field=models.IntegerField(default='6'),
        ),
        migrations.AddField(
            model_name='i_2020_september',
            name='slug_day_7',
            field=models.SlugField(default='rest'),
        ),
    ]
