# Generated by Django 3.1 on 2021-01-19 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0011_auto_20210118_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_dailyplan',
            name='color10',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='color11',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='color12',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='color9',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='session10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='session11',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='session12',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='session9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='slug10',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='slug11',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='slug12',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='m_dailyplan',
            name='slug9',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='Z_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hold1', models.CharField(blank=True, max_length=20)),
                ('rep1', models.CharField(blank=True, max_length=30)),
                ('weight1', models.CharField(blank=True, max_length=30)),
                ('dist1', models.CharField(blank=True, max_length=30)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('hold2', models.CharField(blank=True, max_length=20)),
                ('rep2', models.CharField(blank=True, max_length=30)),
                ('weight2', models.CharField(blank=True, max_length=30)),
                ('dist2', models.CharField(blank=True, max_length=30)),
                ('note2', models.CharField(blank=True, max_length=100)),
                ('hold3', models.CharField(blank=True, max_length=20)),
                ('rep3', models.CharField(blank=True, max_length=30)),
                ('weight3', models.CharField(blank=True, max_length=30)),
                ('dist3', models.CharField(blank=True, max_length=30)),
                ('note3', models.CharField(blank=True, max_length=100)),
                ('hold4', models.CharField(blank=True, max_length=20)),
                ('rep4', models.CharField(blank=True, max_length=30)),
                ('weight4', models.CharField(blank=True, max_length=30)),
                ('dist4', models.CharField(blank=True, max_length=30)),
                ('note4', models.CharField(blank=True, max_length=100)),
                ('hold5', models.CharField(blank=True, max_length=20)),
                ('rep5', models.CharField(blank=True, max_length=30)),
                ('weight5', models.CharField(blank=True, max_length=30)),
                ('dist5', models.CharField(blank=True, max_length=30)),
                ('note5', models.CharField(blank=True, max_length=100)),
                ('hold6', models.CharField(blank=True, max_length=20)),
                ('rep6', models.CharField(blank=True, max_length=30)),
                ('weight6', models.CharField(blank=True, max_length=30)),
                ('dist6', models.CharField(blank=True, max_length=30)),
                ('note6', models.CharField(blank=True, max_length=100)),
                ('hold7', models.CharField(blank=True, max_length=20)),
                ('rep7', models.CharField(blank=True, max_length=30)),
                ('weight7', models.CharField(blank=True, max_length=30)),
                ('dist7', models.CharField(blank=True, max_length=30)),
                ('note7', models.CharField(blank=True, max_length=100)),
                ('hold8', models.CharField(blank=True, max_length=20)),
                ('rep8', models.CharField(blank=True, max_length=30)),
                ('weight8', models.CharField(blank=True, max_length=30)),
                ('dist8', models.CharField(blank=True, max_length=30)),
                ('note8', models.CharField(blank=True, max_length=100)),
                ('hold9', models.CharField(blank=True, max_length=20)),
                ('rep9', models.CharField(blank=True, max_length=30)),
                ('weight9', models.CharField(blank=True, max_length=30)),
                ('dist9', models.CharField(blank=True, max_length=30)),
                ('note9', models.CharField(blank=True, max_length=100)),
                ('hold10', models.CharField(blank=True, max_length=20)),
                ('rep10', models.CharField(blank=True, max_length=30)),
                ('weight10', models.CharField(blank=True, max_length=30)),
                ('dist10', models.CharField(blank=True, max_length=30)),
                ('note10', models.CharField(blank=True, max_length=100)),
                ('hold11', models.CharField(blank=True, max_length=20)),
                ('rep11', models.CharField(blank=True, max_length=30)),
                ('weight11', models.CharField(blank=True, max_length=30)),
                ('dist11', models.CharField(blank=True, max_length=30)),
                ('note11', models.CharField(blank=True, max_length=100)),
                ('hold12', models.CharField(blank=True, max_length=20)),
                ('rep12', models.CharField(blank=True, max_length=30)),
                ('weight12', models.CharField(blank=True, max_length=30)),
                ('dist12', models.CharField(blank=True, max_length=30)),
                ('note12', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
