# Generated by Django 3.1 on 2021-01-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0012_auto_20210119_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug1',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug10',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug11',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug12',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug2',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug3',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug4',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug5',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug6',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug7',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug8',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='m_dailyplan',
            name='slug9',
            field=models.SlugField(default='off'),
        ),
    ]
