# Generated by Django 3.1 on 2021-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0013_auto_20210119_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_data',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
