# Generated by Django 3.1 on 2021-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0014_auto_20210119_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='z_data',
            name='session',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='z_data',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
