# Generated by Django 3.1 on 2021-01-20 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0015_auto_20210120_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z_data',
            old_name='session',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='z_data',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
