# Generated by Django 3.1 on 2021-01-21 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0017_auto_20210121_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_2020_january',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_1',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_2',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_3',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_31',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_32',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_33',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_34',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_35',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_4',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='slug_day_5',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='e_2021_may',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
