# Generated by Django 3.1 on 2021-01-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0022_auto_20210121_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_2022_may',
            name='slug_day_6',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='f_2022_june',
            name='slug_day_33',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='f_2022_june',
            name='slug_day_34',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2021_july',
            name='slug_day_1',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2021_july',
            name='slug_day_2',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2021_july',
            name='slug_day_3',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2022_july',
            name='slug_day_1',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2022_july',
            name='slug_day_2',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2022_july',
            name='slug_day_3',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='g_2022_july',
            name='slug_day_4',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='i_2022_september',
            name='slug_day_34',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='j_2022_october',
            name='slug_day_1',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='j_2022_october',
            name='slug_day_2',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='j_2022_october',
            name='slug_day_3',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='j_2022_october',
            name='slug_day_4',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='j_2022_october',
            name='slug_day_5',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='l_2022_december',
            name='slug_day_1',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='l_2022_december',
            name='slug_day_2',
            field=models.SlugField(default='off'),
        ),
        migrations.AlterField(
            model_name='l_2022_december',
            name='slug_day_3',
            field=models.SlugField(default='off'),
        ),
    ]
