# Generated by Django 3.1 on 2021-01-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0024_auto_20210121_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_2021_november',
            name='color10',
            field=models.CharField(default='rest', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color32',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color33',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color34',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color35',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color36',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color37',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color38',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color39',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color40',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color41',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AlterField(
            model_name='h_2022_august',
            name='color42',
            field=models.CharField(default='off', max_length=20),
        ),
    ]
